version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: danteev/texlive
    steps:
      - checkout
      - run:
          name: Building with pdfLaTeX
          command: |
            pdflatex cormensol.tex
            bibtex cormensol
            pdflatex cormensol.tex
            pdflatex cormensol.tex
      - run:
          name: Deploying document
          command: |
            mkdir target
            cp cormensol.pdf target/cormensol-`date +%Y%m%d%H%M`.pdf
      - store_artifacts:
          path: target/
